name: Share artifact

on:
  pull_request:
    branches:
      - master

jobs:
  share_artifact:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Save README as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: readme
        path: README.md
        retention-days: 1

    - name: Artifacts JSON
      run: |
        curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts
      env:
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_ID: ${{ github.event.pull_request.number }}

    - name: Artifact URL
      run: |
        curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts \
        | grep "archive_download_url" \
        | sed -r 's/\s*"archive_download_url": "([^"]+)",/\1/g'
      env:
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_ID: ${{ github.event.pull_request.number }}

    - name: Notify
      run: |
        # curl -X POST https://pandas.pydata.org/preview-docs/submit/$RUN_ID/$PR_ID/
        curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts \
        | grep "archive_download_url" \
        | sed -r 's/\s*"archive_download_url": "([^"]+)",/\1/g' \
        | xargs curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28"
      env:
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_ID: ${{ github.event.pull_request.number }}
